name: Auto Test

on: [push, pull_request]

jobs:
  test-local-extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run local extraction
        run: python src/extract_data.py

      - name: Validate extracted JSON schema
        run: python src/extract_data_test.py
