name: 简单数据同步

on:
  schedule:
    - cron: '0 18,0,6,12 * * *'
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - run: |
        pip install pandas openpyxl
        python3 assets_check.py
      
      - name: Commit
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add src/data.json || true
          git commit -m "auto" || true
          git push || true
